name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Cache
      uses: actions/cache@v1
      with:
        path: .bundle
        key: bundle-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundle-${{ env.cache-name }}-
          bundle-
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
